name: Chromedp Service Example
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    steps:
      - name: Start chrome
        run: docker run -d -p 9222:9222 --rm --name headless-shell --shm-size 2G chromedp/headless-shell
      - name: Check out repository code
        uses: actions/checkout@v3
      - name:
        run: wget http://www.abc.se
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: docker ps
        run: docker ps 
      - name: Build
        run: go build ./...
      - name: ok
        run: |
          ./e2e-google-chromedp
